# Generated by Django 4.1.6 on 2023-02-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
